config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  
    root "home#index"

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }

    get '/moon', to: 'application#moon', as: 'moon'
    get '/sun', to: 'application#sun', as: 'sun'

    get '/contact', to: "contact#index"
    get '/code_of_conduct', to: "code_of_conduct#index"
    get '/terms_of_use', to: "terms_of_use#index"
    get '/privacy_police', to: "privacy_police#index"

    get '/dashboard', to: "dashboard#index"
    get '/dashboard/articles', to: "dashboard#articles"
    get '/dashboard/follows', to: "dashboard#follows"
    get '/dashboard/profile', to: "dashboard#profile"
    get '/dashboard/settings', to: "dashboard#settings"
    get '/dashboard/stats', to: "dashboard#stats"
    get '/dashboard/data', to: "dashboard#data"
    get '/dashboard/videos', to: "dashboard#videos"
    get '/dashboard/podcasts', to: "dashboard#podcasts"
    get '/dashboard/jobs', to: "dashboard#jobs"
    get '/dashboard/discuss', to: "dashboard#discuss"
    get '/dashboard/saved_articles', to: "dashboard#saved_articles"
    get '/dashboard/liked_articles', to: "dashboard#liked_articles"

    resources :articles do resources :comments end
    resources :videos do resources :video_comments end
    resources :podcasts do resources :video_comments end

    put '/articles/:id/like', to: "articles#like", as: 'like'
    delete '/articles/:id/unlike', to: "articles#unlike", as: 'unlike'

    put '/articles/:id/store', to: "articles#store", as: 'store'
    delete '/articles/:id/unstore', to: "articles#unstore", as: 'unstore'

    put '/videos/:id/video_like', to: "videos#video_like", as: 'video_like'
    delete '/videos/:id/video_unlike', to: "videos#video_unlike", as: 'video_unlike'

  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
    include Visible
    has_many :video_comments, dependent: :destroy

    has_many :video_likes, dependent: :destroy
    def video_liked?(user)
        !!self.video_likes.find{|video_like| video_like.user_id == user.id}
    end

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

    VALID_STATUSES = ['public','private','archived']

    validates :status, inclusion: { in: VALID_STATUSES }

    def archived?
        status == 'archived'
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show]
  def index
    @videos = Video.all
  end

  def show
    @video = Video.find(params[:id])
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(video_params)

    if @video.save
      redirect_to @video
    else
      render :new
    end
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])

    if @video.update(video_params)
      redirect_to @video
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    redirect_to root_path
  end

  def video_like
    @video = Video.all.find(params[:id])
    Video_Like.create(user_id: current_user.id, video_id: @video.id, video_path: video_url, video_title: @video.title)
    redirect_to video_path(@video)
  end

  def video_unlike
    @video = Video.all.find(params[:id])
    Video_Like.where(video_id: @video).destroy_all
    redirect_to video_path(@video)
  end

  private
    def video_params
      params.require(:video).permit(:title,:body,:status)
    end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with model: @video do |form| %>
<div>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% @video.errors.full_messages_for(:title).each do |message| %>
    <div class="alert alert-danger" role="alert"><%= message %></div>
    <% end %>
</div>

<div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% video.errors.full_messages_for(:description).each do |message| %>
    <div class="alert alert-danger" role="alert"><%= message %></div>
    <% end %>
</div>

<div>
    <%= form.label :body %>
    <%= form.text_area :body %>
    <% @video.errors.full_messages_for(:body).each do |message| %>
    <%= message %>
    <% end %>
</div>

<div>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
</div>

<div>
    <%= form.hidden_field :user_id, value: current_user.id %>
</div>

<div>
    <%= form.hidden_field :user_email, value: current_user.email %>
</div>

<br>

<div>
    <%= form.submit %>
</div>
<% end %>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>

<%= render "videos/form", video: @video %>

app/views/videos/index.html.erb
<div class="container" style="margin-top: 5em;">
    <div class="row bg-dark p-3 mt-4 mb-4">
        <h1>Videos</h1>
        <h6 class="text-primary"><%= Video.public_count %> videos in the
            database and counting!</h6>
    </div>

    <div class="row row-cols-1 row-cols-md-2 g-4">

        <% @videos.each do |video| %>
        <% unless video.archived? %>

        <div class="col-4">
            <div class="card bg-dark h-100">

                <img src="https://via.placeholder.com/300x150/000000"
                    class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">
                        <%= link_to video.title, video_path(video) %></h5>
                    <p class="card-text"><%= video.description %></p>
                </div>
                <div class="card-footer">
                    <span class="d-flex flex-row-reverse">
                        <% if user_signed_in? %>
                        <%= link_to "Like", video_path(video), class: 'btn btn-danger btn-sm' %>&ensp;
                        <%= link_to "Save", video_path(video), class: 'btn btn-success btn-sm'  %>&ensp;
                        <% end %>
                        <%= link_to "Show", video_path(video), class: 'btn btn-primary btn-sm'  %>
                    </span>
                    <div class="d-flex">
                        <small
                            class="d-flex flex-row text-warning"><%= video.video_comments.count %>
                            Comment(s)</small>&emsp;
                        <small
                            class="d-flex flex-row text-danger"><%= video.video_likes.count %>
                            Like(s)</small>
                    </div>
                </div>

            </div>
        </div>

        <% end %>
        <% end %>

        <%= link_to "New Video", new_video_path %>

    </div>
</div>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render "videos/form", video: @video %>

app/views/videos/show.html.erb
<h1><%= @video.title %></h1>

<p><%= markdown(@video.body) %></p>

<ul>
    <li><%= link_to "Edit", edit_video_path(@video) %></li>
    <li><%= link_to "Destroy", video_path(@video), method: :delete, data: { confirm: "Are you sure?" } %>
    </li>
</ul>

<h2>Comments</h2>

<%= render @video.video_comments %>

<h2>Add a comment:</h2>

<%= render 'video_comments/form' %>