config/routes.rb
Rails.application.routes.draw do
  
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  
    root "home#index"

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations'
    }

    get '/moon', to: 'application#moon', as: 'moon'
    get '/sun', to: 'application#sun', as: 'sun'

    get '/contact', to: "contact#index"
    get '/code_of_conduct', to: "code_of_conduct#index"
    get '/terms_of_use', to: "terms_of_use#index"
    get '/privacy_police', to: "privacy_police#index"

    get '/dashboard', to: "dashboard#index"
    get '/dashboard/articles', to: "dashboard#articles"
    get '/dashboard/follows', to: "dashboard#follows"
    get '/dashboard/profile', to: "dashboard#profile"
    get '/dashboard/settings', to: "dashboard#settings"
    get '/dashboard/stats', to: "dashboard#stats"
    get '/dashboard/data', to: "dashboard#data"
    get '/dashboard/videos', to: "dashboard#videos"
    get '/dashboard/podcasts', to: "dashboard#podcasts"
    get '/dashboard/jobs', to: "dashboard#jobs"
    get '/dashboard/discuss', to: "dashboard#discuss"
    get '/dashboard/saved_articles', to: "dashboard#saved_articles"
    get '/dashboard/liked_articles', to: "dashboard#liked_articles"

    resources :articles do resources :comments end
    resources :videos do resources :video_comments end
    resources :podcasts do resources :video_comments end

    put '/articles/:id/like', to: "articles#like", as: 'like'
    delete '/articles/:id/unlike', to: "articles#unlike", as: 'unlike'

    put '/articles/:id/store', to: "articles#store", as: 'store'
    delete '/articles/:id/unstore', to: "articles#unstore", as: 'unstore'

    put '/videos/:id/video_like', to: "videos#video_like", as: 'video_like'
    delete '/videos/:id/video_unlike', to: "videos#video_unlike", as: 'video_unlike'

  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  def liked?(user)
      !!self.likes.find{|like| like.user_id == user.id}
  end

  has_many :stores, dependent: :destroy
  def stored?(user)
      !!self.stores.find{|store| store.user_id == user.id}
  end

  VALID_STATUSES = ['public','private','archived']

  validates :status, inclusion: { in: VALID_STATUSES }
  
  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
end

app/models/discussion.rb
class Discussion < ApplicationRecord
      belongs_to :article

  include Visible
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  def liked?(user)
      !!self.likes.find{|like| like.user_id == user.id}
  end

  has_many :stores, dependent: :destroy
  def stored?(user)
      !!self.stores.find{|store| store.user_id == user.id}
  end

  
  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}
end

app/models/help.rb
class Help < ApplicationRecord
      belongs_to :article

  include Visible
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  def liked?(user)
      !!self.likes.find{|like| like.user_id == user.id}
  end

  has_many :stores, dependent: :destroy
  def stored?(user)
      !!self.stores.find{|store| store.user_id == user.id}
  end

  
  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  belongs_to :video
  belongs_to :podcast

  validates :user_id, uniqueness: {scope: :article_id}
  validates :user_id, uniqueness: {scope: :video_id}
  validates :user_id, uniqueness: {scope: :podcast_id}
end

app/models/listing.rb
class Listing < ApplicationRecord
      belongs_to :article

  include Visible
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  def liked?(user)
      !!self.likes.find{|like| like.user_id == user.id}
  end

  has_many :stores, dependent: :destroy
  def stored?(user)
      !!self.stores.find{|store| store.user_id == user.id}
  end

  
  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}
end

app/models/news.rb
class News < ApplicationRecord
      belongs_to :article

  include Visible
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  def liked?(user)
      !!self.likes.find{|like| like.user_id == user.id}
  end

  has_many :stores, dependent: :destroy
  def stored?(user)
      !!self.stores.find{|store| store.user_id == user.id}
  end

  
  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy
  
  has_many :likes, dependent: :destroy
  def liked?(user)
      !!self.likes.find{|like| like.user_id == user.id}
  end

  has_many :stores, dependent: :destroy
  def stored?(user)
      !!self.stores.find{|store| store.user_id == user.id}
  end

  VALID_STATUSES = ['public','private','archived']

  validates :status, inclusion: { in: VALID_STATUSES }
  
  def self.search(search)
    # Title is for the above case, the OP incorrectly had 'name'
    where("title LIKE ?", "%#{search}%")
  end

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  belongs_to :article
  belongs_to :video
  belongs_to :podcast
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
    include Visible
    has_many :video_comments, dependent: :destroy

    has_many :video_likes, dependent: :destroy
    def video_liked?(user)
        !!self.video_likes.find{|video_like| video_like.user_id == user.id}
    end

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

    VALID_STATUSES = ['public','private','archived']

    validates :status, inclusion: { in: VALID_STATUSES }

    def archived?
        status == 'archived'
    end
end

app/models/video_comment.rb
class VideoComment < ApplicationRecord
  include Visible
  belongs_to :video
end

app/models/video_like.rb
class VideoLike < ApplicationRecord
  belongs_to :user
  belongs_to :video
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]

  def index
    @articles = Article.all.limit(10).order('created_at DESC')
    @videos = Video.all.limit(5).order('created_at DESC')
    @podcasts = Podcast.all.limit(5).order('created_at DESC')
  end

  def show
    @article = Article.find(params[:id])
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/home/index.html.erb
<!-- <% if current_user.nil? %>
	<%= link_to new_user_session_path, class: 'login-button' do %>Sign in<% end %>
<% else %>
	<%= link_to articles_path, class: 'login-button' do %>Go to App<% end %>
	<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
<% end %> -->


<div class="container"  style="margin-top: 4em;">
  <div class="row">
    <div class="col mobile-display-none">

    <div class="card mt-4 w-100 bg-dark text-light">
        <%= image_tag "cb_wallpaper-black-logo-v4-purple-transparent.png", class: 'w-100' %>
        <div class="card-body">
        <h5 class="card-title">CodeBatch</h5>
        <p class="card-text"><%= t('home.index.description.html') %></p>
        <div class="d-grid gap-2">
        <% if user_signed_in? %>
            <div class="d-flex justify-content-center"><%= current_user.email %></div>
            <%= link_to destroy_user_session_path, class: 'btn btn-danger', method: :delete do %>Log out<% end %>
            <% else %>

            <%= link_to('Sign up', new_user_registration_path, class: 'btn btn-primary') %>
            <%= link_to('Log in', new_user_session_path, class: 'btn btn-dark')  %>  
        <% end %>
        </div>
        </div>
    </div>

      
    <ol class="list-group list-group-numbered mt-4">
    <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-light">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Subheading</div>
        Cras justo odio
      </div>
      <span class="badge bg-success rounded-pill"># new</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-light">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Subheading</div>
        Cras justo odio
      </div>
      <span class="badge bg-success rounded-pill"># new</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-light">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Subheading</div>
        Cras justo odio
      </div>
      <span class="badge bg-success rounded-pill"># new</span>
    </li>
  </ol>


  <div class="card mt-4 w-100 bg-dark text-light">
        <div class="card-body">
        <h5 class="card-title">Tags</h5>
        </div>
    </div>


    <div class="list-group mt-4 position-relative">
    <span style="z-index: 100;" class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6">Listings</span>
        <div class="list-group-item list-group-item-action bg-dark"></div>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A second link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A third link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A fourth link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark" tabindex="-1" aria-disabled="true">A disabled link item</a>
    </div>

    <div class="list-group mt-4 position-relative">
    <span style="z-index: 100;" class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6">Podcasts</span>
        <div class="list-group-item list-group-item-action bg-dark"></div>
        <% @podcasts.each do |podcast| %>
          <%= link_to podcast.title, podcast, class: "list-group-item list-group-item-action bg-dark" %>
        <% end %>
    </div>

    <div class="list-group mt-4 position-relative">
    <span style="z-index: 100;" class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6">Videos</span>
      <div class="list-group-item list-group-item-action bg-dark"></div>
        <% @videos.each do |video| %>
          <%= link_to video.title, video, class: "list-group-item list-group-item-action bg-dark" %>
        <% end %>
      
    </div>


    </div>
    <div class="col-sm-12 col-lg-6">

    <div class="row row-cols-1 row-cols-md-2 g-4 mt-1">

    <% @articles.each do |article| %>
      <% unless article.archived? %>

      <div class="col-12 col-md-12">
        
        <div class="card bg-dark h-100">
          <img src="https://via.placeholder.com/300x150/000000" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article %></h5>
            <p class="card-text"><%= article.description %></p>
          </div>
          <div class="card-footer">
            <span class="d-flex flex-row-reverse">
            <% if user_signed_in? %>
              <%= link_to "Like", article_path(article), class: 'btn btn-danger btn-sm' %>&ensp;
              <%= link_to "Save", article_path(article), class: 'btn btn-success btn-sm'  %>&ensp;
            <% end %>
              <%= link_to "Show", article_path(article), class: 'btn btn-primary btn-sm'  %>
            </span>
            <div class="d-flex">
            <small class="d-flex flex-row text-warning"><%= article.comments.count %> Comment(s)</small>&emsp;
            <small class="d-flex flex-row text-danger"><%= article.likes.count %> Like(s)</small>
            </div>
          </div>
        </div>

      </div>

      <% end %>
      <% end %>

    </div>


    </div>
    <div class="col mobile-display-none">

    <div class="card mt-4 w-100 bg-dark text-light position-relative">
    <span class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6">CodeBatch Shop</span>
        <div class="card-body">
        <%= image_tag "shop.jpg", class: 'w-100 mt-2' %>
        <p class="card-text text-warning mt-2">
        # new products arrived !!
        </p>
        
        <div class="d-grid gap-2">
        <button class="btn btn-primary">Visit Shop</button>
        </div>
        </div>
    </div>

      
    <ol class="list-group list-group-numbered mt-4">
    <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-light">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Subheading</div>
        Cras justo odio
      </div>
      <span class="badge bg-success rounded-pill"># new</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-light">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Subheading</div>
        Cras justo odio
      </div>
      <span class="badge bg-success rounded-pill"># new</span>
    </li>
    <li class="list-group-item d-flex justify-content-between align-items-start bg-dark text-light">
      <div class="ms-2 me-auto">
        <div class="fw-bold">Subheading</div>
        Cras justo odio
      </div>
      <span class="badge bg-success rounded-pill"># new</span>
    </li>
  </ol>


    <div class="list-group mt-4 position-relative">
    <span style="z-index: 100;" class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6"># news</span>
        <div class="list-group-item list-group-item-action bg-dark"></div>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A second link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A third link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A fourth link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A disabled link item</a>
    </div>

    <div class="list-group mt-4 position-relative">
    <span style="z-index: 100;" class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6"># discuss</span>
        <div class="list-group-item list-group-item-action bg-dark"></div>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A second link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A third link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A fourth link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A disabled link item</a>
    </div>

    <div class="list-group mt-4 position-relative">
    <span style="z-index: 100;" class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6"># help</span>
        <div class="list-group-item list-group-item-action bg-dark"></div>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A second link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A third link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A fourth link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A disabled link item</a>
    </div>

    <div class="list-group mt-4 position-relative">
    <span style="z-index: 100;" class="badge bg-primary rounded-pill top-0 start-50 position-absolute translate-middle fs-6"># jobs</span>
        <div class="list-group-item list-group-item-action bg-dark"></div>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A second link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A third link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A fourth link item</a>
        <a href="#" class="list-group-item list-group-item-action bg-dark">A disabled link item</a>
    </div>

    </div>
  </div>
</div>